name: publish idals

on:
  push:
    tags:
      - "idals-v*"
  workflow_dispatch:
    inputs:
      target:
        description: "publish target"
        required: true
        default: testpypi
        type: choice
        options:
          - testpypi
          - pypi

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: build distribution
        run: |
          python -m pip install --upgrade build twine
          python -m build idals
          python -m twine check idals/dist/*
      - name: upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: idals-dist
          path: idals/dist/

  publish-testpypi:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi' }}
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/idals
    steps:
      - name: download distribution
        uses: actions/download-artifact@v4
        with:
          name: idals-dist
          path: dist/
      - name: publish to testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/

  publish-pypi:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.target == 'pypi') }}
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/idals
    steps:
      - name: download distribution
        uses: actions/download-artifact@v4
        with:
          name: idals-dist
          path: dist/
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
