name: ida-codemode-api tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  ida-codemode-api-tests:
    name: ida-codemode-api tests on IDA ${{ matrix.ida.version }} / Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]
        ida:
          - version: "9.0"
            tag: "ida-pro:9.0"
          - version: "9.1"
            tag: "ida-pro:9.1"
          - version: "9.2"
            tag: "ida-pro:9.2"
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
    - name: Install Python dependencies
      run: |
        pip install idapro ida-domain pytest
        pip install --editable ida-codemode-api
    - name: Install IDA ${{ matrix.ida.version }}
      run: |
        uv run --with ida-hcli hcli --disable-updates ida install --download-id ${{ matrix.ida.tag }} --license-id ${{ secrets.IDA_LICENSE_ID }} --set-default --yes
      env:
        HCLI_API_KEY: ${{ secrets.HCLI_API_KEY }}
        IDA_LICENSE_ID: ${{ secrets.IDA_LICENSE_ID }}
    - name: Run ida-codemode-api tests
      if: ${{ env.IDA_LICENSE_ID != 0 }}
      run: |
        python -m pytest ida-codemode-api/tests/ -v
      env:
        IDA_LICENSE_ID: ${{ secrets.IDA_LICENSE_ID }}
